input {
  beats {
    port => 5044
    client_inactivity_timeout => 0
    ssl => false
  }
}

#filter {
#  if [fields][log_format] == "json" {
#    json {
#      source => "message"
#    }
#  }
#}

output {
    elasticsearch {
      hosts => "192.168.0.10"
      index => "apps-%{+YYYY.MM.dd}"
    }
}
#      template => "/etc/elk/config/logstash_router/storebrand_template.json"
